name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.8

    - name: Checks
      run: make checks

    - name: Unit Tests
      run: make unit-tests

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.65.0
        components: clippy, rustfmt

    - name: Debug build
      working-directory: ./integration/rust_signer/
      run: cargo build --all-targets

    - name: Integration Tests
      run: go test github.com/hyperledger/aries-bbs-go/integration
